export interface PContentItem {
  content: string
  rendered: string
  // from 0 to 1
  width: number
  height: number
}

export interface PCell {
  // autogenerated by database
  key: number
  // manually setted by lexorank strategy
  rank: string
  content: PContentItem[][]
}
